interface seedCountry {
    name: string;
    id: string;
    continent: string;
}

export const countries: seedCountry[] = [
    { name: "Afghanistan", id: "AF", continent: "Asia" },
    { name: "Aland Islands", id: "AX", continent: "Europe" },
    { name: "Albania", id: "AL", continent: "Europe" },
    { name: "Algeria", id: "DZ", continent: "Africa" },
    { name: "American Samoa", id: "AS", continent: "Oceania" },
    { name: "Andorra", id: "AD", continent: "Europe" },
    { name: "Angola", id: "AO", continent: "Africa" },
    { name: "Anguilla", id: "AI", continent: "NorthAmerica" },
    { name: "Antarctica", id: "AQ", continent: "Antarctica" },
    { name: "Antigua and Barbuda", id: "AG", continent: "NorthAmerica" },
    { name: "Argentina", id: "AR", continent: "SouthAmerica" },
    { name: "Armenia", id: "AM", continent: "Asia" },
    { name: "Aruba", id: "AW", continent: "NorthAmerica" },
    { name: "Australia", id: "AU", continent: "Oceania" },
    { name: "Austria", id: "AT", continent: "Europe" },
    { name: "Azerbaijan", id: "AZ", continent: "Asia" },
    { name: "Bahamas", id: "BS", continent: "NorthAmerica" },
    { name: "Bahrain", id: "BH", continent: "Asia" },
    { name: "Bangladesh", id: "BD", continent: "Asia" },
    { name: "Barbados", id: "BB", continent: "NorthAmerica" },
    { name: "Belarus", id: "BY", continent: "Europe" },
    { name: "Belgium", id: "BE", continent: "Europe" },
    { name: "Belize", id: "BZ", continent: "NorthAmerica" },
    { name: "Benin", id: "BJ", continent: "Africa" },
    { name: "Bermuda", id: "BM", continent: "NorthAmerica" },
    { name: "Bhutan", id: "BT", continent: "Asia" },
    { name: "Bolivia", id: "BO", continent: "SouthAmerica" },
    { name: "Bosnia and Herzegovina", id: "BA", continent: "Europe" },
    { name: "Botswana", id: "BW", continent: "Africa" },
    { name: "Bouvet Island", id: "BV", continent: "Antarctica" },
    { name: "Brazil", id: "BR", continent: "SouthAmerica" },
    { name: "British Indian Ocean Territory", id: "IO", continent: "Asia" },
    { name: "Brunei Darussalam", id: "BN", continent: "Asia" },
    { name: "Bulgaria", id: "BG", continent: "Europe" },
    { name: "Burkina Faso", id: "BF", continent: "Africa" },
    { name: "Burundi", id: "BI", continent: "Africa" },
    { name: "Cambodia", id: "KH", continent: "Asia" },
    { name: "Cameroon", id: "CM", continent: "Africa" },
    { name: "Canada", id: "CA", continent: "NorthAmerica" },
    { name: "Cape Verde", id: "CV", continent: "Africa" },
    { name: "Cayman Islands", id: "KY", continent: "NorthAmerica" },
    { name: "Central African Republic", id: "CF", continent: "Africa" },
    { name: "Chad", id: "TD", continent: "Africa" },
    { name: "Chile", id: "CL", continent: "SouthAmerica" },
    { name: "China", id: "CN", continent: "Asia" },
    { name: "Christmas Island", id: "CX", continent: "Asia" },
    { name: "Cocos (Keeling) Islands", id: "CC", continent: "Asia" },
    { name: "Colombia", id: "CO", continent: "SouthAmerica" },
    { name: "Comoros", id: "KM", continent: "Africa" },
    { name: "Congo", id: "CG", continent: "Africa" },
    { name: "Congo, The Democratic Republic of the", id: "CD", continent: "Africa" },
    { name: "Cook Islands", id: "CK", continent: "Oceania" },
    { name: "Costa Rica", id: "CR", continent: "NorthAmerica" },
    { name: "Cote D'Ivoire", id: "CI", continent: "Africa" },
    { name: "Croatia", id: "HR", continent: "Europe" },
    { name: "Cuba", id: "CU", continent: "NorthAmerica" },
    { name: "Cyprus", id: "CY", continent: "Europe" },
    { name: "Czech Republic", id: "CZ", continent: "Europe" },
    { name: "Denmark", id: "DK", continent: "Europe" },
    { name: "Djibouti", id: "DJ", continent: "Africa" },
    { name: "Dominica", id: "DM", continent: "NorthAmerica" },
    { name: "Dominican Republic", id: "DO", continent: "NorthAmerica" },
    { name: "Ecuador", id: "EC", continent: "SouthAmerica" },
    { name: "Egypt", id: "EG", continent: "Africa" },
    { name: "El Salvador", id: "SV", continent: "NorthAmerica" },
    { name: "Equatorial Guinea", id: "GQ", continent: "Africa" },
    { name: "Eritrea", id: "ER", continent: "Africa" },
    { name: "Estonia", id: "EE", continent: "Europe" },
    { name: "Ethiopia", id: "ET", continent: "Africa" },
    { name: "Falkland Islands (Malvinas)", id: "FK", continent: "SouthAmerica" },
    { name: "Faroe Islands", id: "FO", continent: "Europe" },
    { name: "Fiji", id: "FJ", continent: "Oceania" },
    { name: "Finland", id: "FI", continent: "Europe" },
    { name: "France", id: "FR", continent: "Europe" },
    { name: "French Guiana", id: "GF", continent: "SouthAmerica" },
    { name: "French Polynesia", id: "PF", continent: "Oceania" },
    { name: "French Southern Territories", id: "TF", continent: "Antarctica" },
    { name: "Gabon", id: "GA", continent: "Africa" },
    { name: "Gambia", id: "GM", continent: "Africa" },
    { name: "Georgia", id: "GE", continent: "Asia" },
    { name: "Germany", id: "DE", continent: "Europe" },
    { name: "Ghana", id: "GH", continent: "Africa" },
    { name: "Gibraltar", id: "GI", continent: "Europe" },
    { name: "Greece", id: "GR", continent: "Europe" },
    { name: "Greenland", id: "GL", continent: "NorthAmerica" },
    { name: "Grenada", id: "GD", continent: "NorthAmerica" },
    { name: "Guadeloupe", id: "GP", continent: "NorthAmerica" },
    { name: "Guam", id: "GU", continent: "Oceania" },
    { name: "Guatemala", id: "GT", continent: "NorthAmerica" },
    { name: "Guernsey", id: "GG", continent: "Europe" },
    { name: "Guinea", id: "GN", continent: "Africa" },
    { name: "Guinea-Bissau", id: "GW", continent: "Africa" },
    { name: "Guyana", id: "GY", continent: "SouthAmerica" },
    { name: "Haiti", id: "HT", continent: "NorthAmerica" },
    { name: "Heard Island and Mcdonald Islands", id: "HM", continent: "Antarctica" },
    { name: "Holy See (Vatican City State)", id: "VA", continent: "Europe" },
    { name: "Honduras", id: "HN", continent: "NorthAmerica" },
    { name: "Hong Kong", id: "HK", continent: "Asia" },
    { name: "Hungary", id: "HU", continent: "Europe" },
    { name: "Iceland", id: "IS", continent: "Europe" },
    { name: "India", id: "IN", continent: "Asia" },
    { name: "Indonesia", id: "ID", continent: "Asia" },
    { name: "Iran, Islamic Republic Of", id: "IR", continent: "Asia" },
    { name: "Iraq", id: "IQ", continent: "Asia" },
    { name: "Ireland", id: "IE", continent: "Europe" },
    { name: "Isle of Man", id: "IM", continent: "Europe" },
    { name: "Israel", id: "IL", continent: "Asia" },
    { name: "Italy", id: "IT", continent: "Europe" },
    { name: "Jamaica", id: "JM", continent: "NorthAmerica" },
    { name: "Japan", id: "JP", continent: "Asia" },
    { name: "Jersey", id: "JE", continent: "Europe" },
    { name: "Jordan", id: "JO", continent: "Asia" },
    { name: "Kazakhstan", id: "KZ", continent: "Asia" },
    { name: "Kenya", id: "KE", continent: "Africa" },
    { name: "Kiribati", id: "KI", continent: "Oceania" },
    { name: "Korea, Democratic People'S Republic of", id: "KP", continent: "Asia" },
    { name: "Korea, Republic of", id: "KR", continent: "Asia" },
    { name: "Kuwait", id: "KW", continent: "Asia" },
    { name: "Kyrgyzstan", id: "KG", continent: "Asia" },
    { name: "Lao People'S Democratic Republic", id: "LA", continent: "Asia" },
    { name: "Latvia", id: "LV", continent: "Europe" },
    { name: "Lebanon", id: "LB", continent: "Asia" },
    { name: "Lesotho", id: "LS", continent: "Africa" },
    { name: "Liberia", id: "LR", continent: "Africa" },
    { name: "Libyan Arab Jamahiriya", id: "LY", continent: "Africa" },
    { name: "Liechtenstein", id: "LI", continent: "Europe" },
    { name: "Lithuania", id: "LT", continent: "Europe" },
    { name: "Luxembourg", id: "LU", continent: "Europe" },
    { name: "Macao", id: "MO", continent: "Europe" },
    { name: "Macedonia, The Former Yugoslav Republic of", id: "MK", continent: "Europe" },
    { name: "Madagascar", id: "MG", continent: "Europe" },
    { name: "Malawi", id: "MW", continent: "Europe" },
    { name: "Malaysia", id: "MY", continent: "Europe" },
    { name: "Maldives", id: "MV", continent: "Europe" },
    { name: "Mali", id: "ML", continent: "Europe" },
    { name: "Malta", id: "MT", continent: "Europe" },
    { name: "Marshall Islands", id: "MH", continent: "Europe" },
    { name: "Martinique", id: "MQ", continent: "Europe" },
    { name: "Mauritania", id: "MR", continent: "Europe" },
    { name: "Mauritius", id: "MU", continent: "Europe" },
    { name: "Mayotte", id: "YT", continent: "Europe" },
    { name: "Mexico", id: "MX", continent: "Europe" },
    { name: "Micronesia, Federated States of", id: "FM", continent: "Europe" },
    { name: "Moldova, Republic of", id: "MD", continent: "Europe" },
    { name: "Monaco", id: "MC", continent: "Europe" },
    { name: "Mongolia", id: "MN", continent: "Europe" },
    { name: "Montserrat", id: "MS", continent: "Europe" },
    { name: "Morocco", id: "MA", continent: "Europe" },
    { name: "Mozambique", id: "MZ", continent: "Europe" },
    { name: "Myanmar", id: "MM", continent: "Europe" },
    { name: "Namibia", id: "NA", continent: "Europe" },
    { name: "Nauru", id: "NR", continent: "Europe" },
    { name: "Nepal", id: "NP", continent: "Europe" },
    { name: "Netherlands", id: "NL", continent: "Europe" },
    { name: "Netherlands Antilles", id: "AN", continent: "Europe" },
    { name: "New Caledonia", id: "NC", continent: "Europe" },
    { name: "New Zealand", id: "NZ", continent: "Europe" },
    { name: "Nicaragua", id: "NI", continent: "Europe" },
    { name: "Niger", id: "NE", continent: "Europe" },
    { name: "Nigeria", id: "NG", continent: "Europe" },
    { name: "Niue", id: "NU", continent: "Europe" },
    { name: "Norfolk Island", id: "NF", continent: "Europe" },
    { name: "Northern Mariana Islands", id: "MP", continent: "Europe" },
    { name: "Norway", id: "NO", continent: "Europe" },
    { name: "Oman", id: "OM", continent: "Europe" },
    { name: "Pakistan", id: "PK", continent: "Europe" },
    { name: "Palau", id: "PW", continent: "Europe" },
    { name: "Palestinian Territory, Occupied", id: "PS", continent: "Europe" },
    { name: "Panama", id: "PA", continent: "Europe" },
    { name: "Papua New Guinea", id: "PG", continent: "Europe" },
    { name: "Paraguay", id: "PY", continent: "Europe" },
    { name: "Peru", id: "PE", continent: "Europe" },
    { name: "Philippines", id: "PH", continent: "Europe" },
    { name: "Pitcairn", id: "PN", continent: "Europe" },
    { name: "Poland", id: "PL", continent: "Europe" },
    { name: "Portugal", id: "PT", continent: "Europe" },
    { name: "Puerto Rico", id: "PR", continent: "Europe" },
    { name: "Qatar", id: "QA", continent: "Europe" },
    { name: "Reunion", id: "RE", continent: "Europe" },
    { name: "Romania", id: "RO", continent: "Europe" },
    { name: "Russian Federation", id: "RU", continent: "Europe" },
    { name: "RWANDA", id: "RW", continent: "Europe" },
    { name: "Saint Helena", id: "SH", continent: "Europe" },
    { name: "Saint Kitts and Nevis", id: "KN", continent: "Europe" },
    { name: "Saint Lucia", id: "LC", continent: "Europe" },
    { name: "Saint Pierre and Miquelon", id: "PM", continent: "Europe" },
    { name: "Saint Vincent and the Grenadines", id: "VC", continent: "Europe" },
    { name: "Samoa", id: "WS", continent: "Europe" },
    { name: "San Marino", id: "SM", continent: "Europe" },
    { name: "Sao Tome and Principe", id: "ST", continent: "Europe" },
    { name: "Saudi Arabia", id: "SA", continent: "Europe" },
    { name: "Senegal", id: "SN", continent: "Europe" },
    { name: "Serbia and Montenegro", id: "CS", continent: "Europe" },
    { name: "Seychelles", id: "SC", continent: "Europe" },
    { name: "Sierra Leone", id: "SL", continent: "Europe" },
    { name: "Singapore", id: "SG", continent: "Europe" },
    { name: "Slovakia", id: "SK", continent: "Europe" },
    { name: "Slovenia", id: "SI", continent: "Europe" },
    { name: "Solomon Islands", id: "SB", continent: "Europe" },
    { name: "Somalia", id: "SO", continent: "Europe" },
    { name: "South Africa", id: "ZA", continent: "Africa" },
    { name: "South Georgia and the South Sandwich Islands", id: "GS", continent: "Antarctica" },
    { name: "Spain", id: "ES", continent: "Europe" },
    { name: "Sri Lanka", id: "LK", continent: "Asia" },
    { name: "Sudan", id: "SD", continent: "Africa" },
    { name: "Suriname", id: "SR", continent: "SouthAmerica" },
    { name: "Svalbard and Jan Mayen", id: "SJ", continent: "Europe" },
    { name: "Swaziland", id: "SZ", continent: "Africa" },
    { name: "Sweden", id: "SE", continent: "Europe" },
    { name: "Switzerland", id: "CH", continent: "Europe" },
    { name: "Syrian Arab Republic", id: "SY", continent: "Asia" },
    { name: "Taiwan, Province of China", id: "TW", continent: "Asia" },
    { name: "Tajikistan", id: "TJ", continent: "Asia" },
    { name: "Tanzania, United Republic of", id: "TZ", continent: "Africa" },
    { name: "Thailand", id: "TH", continent: "Asia" },
    { name: "Timor-Leste", id: "TL", continent: "Asia" },
    { name: "Togo", id: "TG", continent: "Africa" },
    { name: "Tokelau", id: "TK", continent: "Oceania" },
    { name: "Tonga", id: "TO", continent: "Oceania" },
    { name: "Trinidad and Tobago", id: "TT", continent: "NorthAmerica" },
    { name: "Tunisia", id: "TN", continent: "Africa" },
    { name: "Turkey", id: "TR", continent: "Asia" },
    { name: "Turkmenistan", id: "TM", continent: "Asia" },
    { name: "Turks and Caicos Islands", id: "TC", continent: "NorthAmerica" },
    { name: "Tuvalu", id: "TV", continent: "Oceania" },
    { name: "Uganda", id: "UG", continent: "Africa" },
    { name: "Ukraine", id: "UA", continent: "Europe" },
    { name: "United Arab Emirates", id: "AE", continent: "Asia" },
    { name: "United Kingdom", id: "GB", continent: "Europe" },
    { name: "United States", id: "US", continent: "NorthAmerica" },
    { name: "United States Minor Outlying Islands", id: "UM", continent: "NorthAmerica" },
    { name: "Uruguay", id: "UY", continent: "SouthAmerica" },
    { name: "Uzbekistan", id: "UZ", continent: "Asia" },
    { name: "Vanuatu", id: "VU", continent: "Oceania" },
    { name: "Venezuela", id: "VE", continent: "SouthAmerica" },
    { name: "Viet Nam", id: "VN", continent: "Asia" },
    { name: "Virgin Islands, British", id: "VG", continent: "NorthAmerica" },
    { name: "Virgin Islands, U.S.", id: "VI", continent: "NorthAmerica" },
    { name: "Wallis and Futuna", id: "WF", continent: "Oceania" },
    { name: "Western Sahara", id: "EH", continent: "Africa" },
    { name: "Yemen", id: "YE", continent: "Asia" },
    { name: "Zambia", id: "ZM", continent: "Africa" },
    { name: "Zimbabwe", id: "ZW", continent: "Africa" }
];

